Trabajo/evader/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :people
  resources :bills
  resources :clients do
    resources :contacts, except: [:index]
  end

end

Trabajo/evader/app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :client

  enum mediums: { 'phone' => 'phone', 'mail' => 'mail', 'address' => 'address', 'skype' => 'skype' }

  #model validations
  validates :client, :medium, :value,
    presence: true

  #phone validation
  validates :value,
    format: /([\w\-\']{2,})([\s]+)([\w\-\']{2,})/,
    presence: true,
    if: "medium == 'phone'"

  #mail validation
  validates :value,
    format: /@/,
    presence: true,
    if: "medium == 'mail'"

  #address validation
  validates :value,
    length: { minimum: 4, maximum: 255 },
    presence: true,
    if: "medium == 'address'"

  #skype validation
  validates :value,
    length: { minimum: 4, maximum: 255 },
    presence: true,
    if: "medium == 'skype'"

end

Trabajo/evader/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_client

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to Client.find(params[:client_id]), notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to Client.find(params[:client_id]), notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to Client.find(params[:client_id]), notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def set_client
      @client = Client.find(params[:client_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:client_id, :medium, :value)
    end
end

Trabajo/evader/app/helpers/contacts_helper.rb
module ContactsHelper
end

Trabajo/evader/app/views/contacts/_form.html.erb
<%= simple_form_for([@client,@contact]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :client, collection: [@client] %>
    <%= f.input :medium, collection: Contact.mediums %>
    <%= f.input :value %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

Trabajo/evader/app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', client_path(@client) %>

Trabajo/evader/app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Type</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.client %></td>
        <td><%= contact.type %></td>
        <td><%= contact.value %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

Trabajo/evader/app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', client_path(@client) %>

Trabajo/evader/app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @contact.client %>
</p>

<p>
  <strong>Type:</strong>
  <%= @contact.medium %>
</p>

<p>
  <strong>Value:</strong>
  <%= @contact.value %>
</p>

<%= link_to 'Back', client_path(@client) %>