Trabajo/evader/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :people
  resources :bills
  resources :clients do
    resources :contacts, except: [:index]
  end

end

Trabajo/evader/app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :client
  belongs_to :person

  #Model validations

  validates :client, :person,
    presence:true

  validates :description,
    length: {minumum: 2, maximum: 255},
    presence: true

  validates :amount,
    numericality: { greater_than_or_equal_to: 0.00},
    presence: true

  validates :emission_date,
    presence: true

end

Trabajo/evader/app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:client_id, :person_id, :description, :amount, :amount, :emission_date)
    end
end

Trabajo/evader/app/helpers/bills_helper.rb
module BillsHelper
end

Trabajo/evader/app/views/bills/_form.html.erb
<%= simple_form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.association :client %>
  </div>
  <div class="field">
    <%= f.association :person %>
  </div>
  <div class="field">
    <%= f.input :description %>
  </div>
  <div class="field">
    <%= f.input :amount %>
  </div>
  <div class="field">
    <%= f.input :emission_date, :html5 => true %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-default' %>
  </div>
<% end %>

Trabajo/evader/app/views/bills/edit.html.erb
<div class="page-header">
  <h1>Editing Bill</h1>
</div>

<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <%= render 'form' %>

    <%= link_to 'Show', @bill %> |
    <%= link_to 'Back', bills_path %>
  </div>
</div>

Trabajo/evader/app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1>Listing Bills</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Client</th>
      <th>Person</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Emission date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.client %></td>
        <td><%= bill.person %></td>
        <td><%= bill.description %></td>
        <td><%= bill.amount %></td>
        <td><%= bill.emission_date %></td>
        <td><%= link_to 'Show', bill %></td>
        <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
        <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill', new_bill_path, :class => 'btn btn-default' %>

Trabajo/evader/app/views/bills/new.html.erb
<div class="page-header">
  <h1>New Bill</h1>
</div>

<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <%= render 'form' %>
    <%= link_to 'Back', bills_path %>
  </div>
</div>

Trabajo/evader/app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @bill.client %>
</p>

<p>
  <strong>Person:</strong>
  <%= @bill.person %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bill.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @bill.amount %>
</p>

<p>
  <strong>Emission date:</strong>
  <%= @bill.emission_date %>
</p>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>