Trabajo/evader/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :people
  resources :bills
  resources :clients do
    resources :contacts, except: [:index]
  end

end

Trabajo/evader/app/models/client.rb
class Client < ActiveRecord::Base
  has_many :bills, dependent: :restrict_with_error
  has_many :people, through: :bills
  has_many :contacts, dependent: :restrict_with_error

  enum genre: {'male' => 'male', 'female' => 'female'}

  # Model validations
  validates :first_name, :last_name,
    format: /\A[^0-9`!@#\$%\^&*+_=]+\z/,
    length: {minumum: 2, maximum: 50},
    presence: true

  validates :dni,
    presence: true,
    format:  /\A[0-9]+\z/,
    length: { minimum: 6, maximum: 8 }

  validates :gender,
    inclusion: { in: self.genres },
    presence: true

  validates :cui,
    format: /\A\d{2}\-\d{8}\-\d{1}\z/,
    presence: true

  #Model logic
  def to_s
    "#{self.first_name} #{self.last_name}"
  end

  def age
    now = Time.now.utc.to_date
    now.year - birthdate.year - (birthdate.to_date.change(:year => now.year) > now ? 1 : 0)
  end

  def amount_billed_per_year
    self.bills
    .select("strftime('%Y', emission_date) as emission_year, SUM(amount) as yearly_amount")
    .group("strftime('%Y', emission_date)")
    .order("strftime('%Y', emission_date)")
  end

  def emmited_bills_amount_per_month
    self.bills
    .select("strftime('%m', emission_date) as emission_month, SUM(amount) as monthly_amount")
    .where("strftime('%Y', emission_date) = ? ", Time.now.year.to_s )
    .group("strftime('%m', emission_date)")
    .order("strftime('%m', emission_date)")
  end

  def most_billed_people
    self.people
    .select("name, SUM(amount) as billed_amount")
    .group('name')
    .order('billed_amount DESC')
    .limit(5)
  end

end

Trabajo/evader/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :dni, :birthdate, :gender, :cui)
    end
end

Trabajo/evader/app/helpers/clients_helper.rb
module ClientsHelper
end

Trabajo/evader/app/views/clients/_form.html.erb
  <%= simple_form_for(@client) do |f| %>
    <% if @client.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

        <ul>
        <% @client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.input :first_name %>
    </div>
    <div class="field">
      <%= f.input :last_name %>
    </div>
    <div class="field">
      <%= f.input :dni %>
    </div>
    <div class="field">
      <%= f.input :birthdate, :html5 => true %>
    </div>
    <div class="field">
      <%= f.input :gender, collection: Client.genres %>
    </div>
    <div class="field">
      <%= f.input :cui %>
    </div>
    <div class="actions">
      <%= f.submit :class => 'btn btn-default' %>
    </div>
  <% end %>

Trabajo/evader/app/views/clients/edit.html.erb
<div class="page-header">
  <h1>Editing Client</h1>
</div>

<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <%= render 'form' %>
    <%= link_to 'Show', @client %> |
    <%= link_to 'Back', clients_path %>
  </div>
</div>

Trabajo/evader/app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1>Listing Clients</h1>
</div>

<div class="col-xs-12">
  <table class="table">
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>DNI</th>
        <th>Birthdate</th>
        <th>Gender</th>
        <th>Cui</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @clients.each do |client| %>
        <tr>
          <td><%= client.first_name %></td>
          <td><%= client.last_name %></td>
          <td><%= client.dni %></td>
          <td><%= client.birthdate %></td>
          <td><%= client.gender %></td>
          <td><%= client.cui %></td>
          <td><%= link_to 'Show', client %></td>
          <td><%= link_to 'Edit', edit_client_path(client) %></td>
          <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'New Client', new_client_path, :class => 'btn btn-default' %>

</div>

Trabajo/evader/app/views/clients/new.html.erb
<div class="page-header">
  <h1>New Client</h1>
</div>

<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <%= render 'form' %>
    <%= link_to 'Back', clients_path %>
  </div>
</div>

Trabajo/evader/app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1><%= @client.to_s %><small>'s information</small></h1>
</div>
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <h3 class="panel-title">Client info</h3>
        <ul>
          <li>First name: <%= @client.first_name %></li>
          <li>Last name: <%= @client.last_name %></li>
          <li>Birthdate: <%= @client.birthdate %></li>
          <li>Age: <%= @client.age %></li>
          <li>Gender: <%= @client.gender %></li>
          <li>CUIL/CUIT: <%= @client.cui %></li>
        </ul>
        <h3 class="panel-title"> Contact info <%= link_to 'Add contact', new_client_contact_path(@client), :class => 'btn btn-xs btn-default' %></h3>
        <ul>
          <%if @client.contacts.each do |c| %>
            <li>
              <%= c.medium %> : <%= c.value %>
              [
              <%= link_to 'Show', client_contact_path(@client, c) %> |
              <%= link_to 'Edit', edit_client_contact_path(@client, c) %> |
              <%= link_to 'Destroy', client_contact_path(@client, c), method: :delete, data: { confirm: 'Are you sure?' } %>
              ]
            </li>
          <% end.empty? %>
            <li> Client has no contact information </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <h4> Client's yearly billings </h4>
        <ul>
          <%if @client.amount_billed_per_year.each do |yb| %>
            <li> <%= yb.emission_year %> : $<%= yb.yearly_amount %>  </li>
          <% end.empty? %>
            <li> Client has no bills </li>
          <% end %>
        </ul>

        <h4>Client's monthly billing for current year</h4>
        <ul>
          <%if @client.emmited_bills_amount_per_month.each do |mb| %>
            <li> Month <%= mb.emission_month %> : $<%= mb.monthly_amount %>  </li>
          <% end.empty? %>
            <li> Client has no bills </li>
          <% end %>
        </ul>

        <h4>Client's most billed phisical/legal people</h4>
        <ol>
          <%if @client.most_billed_people.each do |mbp| %>
            <li> <%= mbp.name %> : $<%= mbp.billed_amount %> </li>
          <% end.empty? %>
            <li> Client hasn't billed anyone yet </li>
          <% end %>
        </ol>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>